mv /sdcard/Download/ad.png /sdcard/AD.png
mv /sdcard/Download/ae.png /sdcard/AE.png
mv /sdcard/Download/af.png /sdcard/AF.png
mv /sdcard/Download/ag.png /sdcard/AG.png
mv /sdcard/Download/ai.png /sdcard/AI.png
mv /sdcard/Download/al.png /sdcard/AL.png
mv /sdcard/Download/am.png /sdcard/AM.png
mv /sdcard/Download/ao.png /sdcard/AO.png
mv /sdcard/Download/aq.png /sdcard/AQ.png
mv /sdcard/Download/ar.png /sdcard/AR.png
mv /sdcard/Download/as.png /sdcard/AS.png
mv /sdcard/Download/at.png /sdcard/AT.png
mv /sdcard/Download/au.png /sdcard/AU.png
mv /sdcard/Download/aw.png /sdcard/AW.png
mv /sdcard/Download/ax.png /sdcard/AX.png
mv /sdcard/Download/az.png /sdcard/AZ.png
mv /sdcard/Download/ba.png /sdcard/BA.png
mv /sdcard/Download/bb.png /sdcard/BB.png
mv /sdcard/Download/bd.png /sdcard/BD.png
mv /sdcard/Download/be.png /sdcard/BE.png
mv /sdcard/Download/bf.png /sdcard/BF.png
mv /sdcard/Download/bg.png /sdcard/BG.png
mv /sdcard/Download/bh.png /sdcard/BH.png
mv /sdcard/Download/bi.png /sdcard/BI.png
mv /sdcard/Download/bj.png /sdcard/BJ.png
mv /sdcard/Download/bl.png /sdcard/BL.png
mv /sdcard/Download/bm.png /sdcard/BM.png
mv /sdcard/Download/bn.png /sdcard/BN.png
mv /sdcard/Download/bo.png /sdcard/BO.png
mv /sdcard/Download/bq.png /sdcard/BQ.png
mv /sdcard/Download/br.png /sdcard/BR.png
mv /sdcard/Download/bs.png /sdcard/BS.png
mv /sdcard/Download/bt.png /sdcard/BT.png
mv /sdcard/Download/bv.png /sdcard/BV.png
mv /sdcard/Download/bw.png /sdcard/BW.png
mv /sdcard/Download/by.png /sdcard/BY.png
mv /sdcard/Download/bz.png /sdcard/BZ.png
mv /sdcard/Download/ca.png /sdcard/CA.png
mv /sdcard/Download/cc.png /sdcard/CC.png
mv /sdcard/Download/cd.png /sdcard/CD.png
mv /sdcard/Download/cf.png /sdcard/CF.png
mv /sdcard/Download/cg.png /sdcard/CG.png
mv /sdcard/Download/ch.png /sdcard/CH.png
mv /sdcard/Download/ci.png /sdcard/CI.png
mv /sdcard/Download/ck.png /sdcard/CK.png
mv /sdcard/Download/cl.png /sdcard/CL.png
mv /sdcard/Download/cm.png /sdcard/CM.png
mv /sdcard/Download/cn.png /sdcard/CN.png
mv /sdcard/Download/co.png /sdcard/CO.png
mv /sdcard/Download/cr.png /sdcard/CR.png
mv /sdcard/Download/cu.png /sdcard/CU.png
mv /sdcard/Download/cv.png /sdcard/CV.png
mv /sdcard/Download/cw.png /sdcard/CW.png
mv /sdcard/Download/cx.png /sdcard/CX.png
mv /sdcard/Download/cy.png /sdcard/CY.png
mv /sdcard/Download/cz.png /sdcard/CZ.png
mv /sdcard/Download/de.png /sdcard/DE.png
mv /sdcard/Download/dj.png /sdcard/DJ.png
mv /sdcard/Download/dk.png /sdcard/DK.png
mv /sdcard/Download/dm.png /sdcard/DM.png
mv /sdcard/Download/do.png /sdcard/DO.png
mv /sdcard/Download/dz.png /sdcard/DZ.png
mv /sdcard/Download/ec.png /sdcard/EC.png
mv /sdcard/Download/ee.png /sdcard/EE.png
mv /sdcard/Download/eg.png /sdcard/EG.png
mv /sdcard/Download/eh.png /sdcard/EH.png
mv /sdcard/Download/er.png /sdcard/ER.png
mv /sdcard/Download/es.png /sdcard/ES.png
mv /sdcard/Download/et.png /sdcard/ET.png
mv /sdcard/Download/eu.png /sdcard/EU.png
mv /sdcard/Download/fi.png /sdcard/FI.png
mv /sdcard/Download/fj.png /sdcard/FJ.png
mv /sdcard/Download/fk.png /sdcard/FK.png
mv /sdcard/Download/fm.png /sdcard/FM.png
mv /sdcard/Download/fo.png /sdcard/FO.png
mv /sdcard/Download/fr.png /sdcard/FR.png
mv /sdcard/Download/ga.png /sdcard/GA.png
mv /sdcard/Download/gb-eng.png /sdcard/GB-ENG.png
mv /sdcard/Download/gb-nir.png /sdcard/GB-NIR.png
mv /sdcard/Download/gb-sct.png /sdcard/GB-SCT.png
mv /sdcard/Download/gb-wls.png /sdcard/GB-WLS.png
mv /sdcard/Download/gb.png /sdcard/GB.png
mv /sdcard/Download/gd.png /sdcard/GD.png
mv /sdcard/Download/ge.png /sdcard/GE.png
mv /sdcard/Download/gf.png /sdcard/GF.png
mv /sdcard/Download/gg.png /sdcard/GG.png
mv /sdcard/Download/gh.png /sdcard/GH.png
mv /sdcard/Download/gi.png /sdcard/GI.png
mv /sdcard/Download/gl.png /sdcard/GL.png
mv /sdcard/Download/gm.png /sdcard/GM.png
mv /sdcard/Download/gn.png /sdcard/GN.png
mv /sdcard/Download/gp.png /sdcard/GP.png
mv /sdcard/Download/gq.png /sdcard/GQ.png
mv /sdcard/Download/gr.png /sdcard/GR.png
mv /sdcard/Download/gs.png /sdcard/GS.png
mv /sdcard/Download/gt.png /sdcard/GT.png
mv /sdcard/Download/gu.png /sdcard/GU.png
mv /sdcard/Download/gw.png /sdcard/GW.png
mv /sdcard/Download/gy.png /sdcard/GY.png
mv /sdcard/Download/hk.png /sdcard/HK.png
mv /sdcard/Download/hm.png /sdcard/HM.png
mv /sdcard/Download/hn.png /sdcard/HN.png
mv /sdcard/Download/hr.png /sdcard/HR.png
mv /sdcard/Download/ht.png /sdcard/HT.png
mv /sdcard/Download/hu.png /sdcard/HU.png
mv /sdcard/Download/id.png /sdcard/ID.png
mv /sdcard/Download/ie.png /sdcard/IE.png
mv /sdcard/Download/il.png /sdcard/IL.png
mv /sdcard/Download/im.png /sdcard/IM.png
mv /sdcard/Download/in.png /sdcard/IN.png
mv /sdcard/Download/io.png /sdcard/IO.png
mv /sdcard/Download/iq.png /sdcard/IQ.png
mv /sdcard/Download/ir.png /sdcard/IR.png
mv /sdcard/Download/is.png /sdcard/IS.png
mv /sdcard/Download/it.png /sdcard/IT.png
mv /sdcard/Download/je.png /sdcard/JE.png
mv /sdcard/Download/jm.png /sdcard/JM.png
mv /sdcard/Download/jo.png /sdcard/JO.png
mv /sdcard/Download/jp.png /sdcard/JP.png
mv /sdcard/Download/ke.png /sdcard/KE.png
mv /sdcard/Download/kg.png /sdcard/KG.png
mv /sdcard/Download/kh.png /sdcard/KH.png
mv /sdcard/Download/ki.png /sdcard/KI.png
mv /sdcard/Download/km.png /sdcard/KM.png
mv /sdcard/Download/kn.png /sdcard/KN.png
mv /sdcard/Download/kp.png /sdcard/KP.png
mv /sdcard/Download/kr.png /sdcard/KR.png
mv /sdcard/Download/kw.png /sdcard/KW.png
mv /sdcard/Download/ky.png /sdcard/KY.png
mv /sdcard/Download/kz.png /sdcard/KZ.png
mv /sdcard/Download/la.png /sdcard/LA.png
mv /sdcard/Download/lb.png /sdcard/LB.png
mv /sdcard/Download/lc.png /sdcard/LC.png
mv /sdcard/Download/li.png /sdcard/LI.png
mv /sdcard/Download/lk.png /sdcard/LK.png
mv /sdcard/Download/lr.png /sdcard/LR.png
mv /sdcard/Download/ls.png /sdcard/LS.png
mv /sdcard/Download/lt.png /sdcard/LT.png
mv /sdcard/Download/lu.png /sdcard/LU.png
mv /sdcard/Download/lv.png /sdcard/LV.png
mv /sdcard/Download/ly.png /sdcard/LY.png
mv /sdcard/Download/ma.png /sdcard/MA.png
mv /sdcard/Download/mc.png /sdcard/MC.png
mv /sdcard/Download/md.png /sdcard/MD.png
mv /sdcard/Download/me.png /sdcard/ME.png
mv /sdcard/Download/mf.png /sdcard/MF.png
mv /sdcard/Download/mg.png /sdcard/MG.png
mv /sdcard/Download/mh.png /sdcard/MH.png
mv /sdcard/Download/mk.png /sdcard/MK.png
mv /sdcard/Download/ml.png /sdcard/ML.png
mv /sdcard/Download/mm.png /sdcard/MM.png
mv /sdcard/Download/mn.png /sdcard/MN.png
mv /sdcard/Download/mo.png /sdcard/MO.png
mv /sdcard/Download/mp.png /sdcard/MP.png
mv /sdcard/Download/mq.png /sdcard/MQ.png
mv /sdcard/Download/mr.png /sdcard/MR.png
mv /sdcard/Download/ms.png /sdcard/MS.png
mv /sdcard/Download/mt.png /sdcard/MT.png
mv /sdcard/Download/mu.png /sdcard/MU.png
mv /sdcard/Download/mv.png /sdcard/MV.png
mv /sdcard/Download/mw.png /sdcard/MW.png
mv /sdcard/Download/mx.png /sdcard/MX.png
mv /sdcard/Download/my.png /sdcard/MY.png
mv /sdcard/Download/mz.png /sdcard/MZ.png
mv /sdcard/Download/na.png /sdcard/NA.png
mv /sdcard/Download/nc.png /sdcard/NC.png
mv /sdcard/Download/ne.png /sdcard/NE.png
mv /sdcard/Download/nf.png /sdcard/NF.png
mv /sdcard/Download/ng.png /sdcard/NG.png
mv /sdcard/Download/ni.png /sdcard/NI.png
mv /sdcard/Download/nl.png /sdcard/NL.png
mv /sdcard/Download/no.png /sdcard/NO.png
mv /sdcard/Download/np.png /sdcard/NP.png
mv /sdcard/Download/nr.png /sdcard/NR.png
mv /sdcard/Download/nu.png /sdcard/NU.png
mv /sdcard/Download/nz.png /sdcard/NZ.png
mv /sdcard/Download/om.png /sdcard/OM.png
mv /sdcard/Download/pa.png /sdcard/PA.png
mv /sdcard/Download/pe.png /sdcard/PE.png
mv /sdcard/Download/pf.png /sdcard/PF.png
mv /sdcard/Download/pg.png /sdcard/PG.png
mv /sdcard/Download/ph.png /sdcard/PH.png
mv /sdcard/Download/pk.png /sdcard/PK.png
mv /sdcard/Download/pl.png /sdcard/PL.png
mv /sdcard/Download/pm.png /sdcard/PM.png
mv /sdcard/Download/pn.png /sdcard/PN.png
mv /sdcard/Download/pr.png /sdcard/PR.png
mv /sdcard/Download/ps.png /sdcard/PS.png
mv /sdcard/Download/pt.png /sdcard/PT.png
mv /sdcard/Download/pw.png /sdcard/PW.png
mv /sdcard/Download/py.png /sdcard/PY.png
mv /sdcard/Download/qa.png /sdcard/QA.png
mv /sdcard/Download/re.png /sdcard/RE.png
mv /sdcard/Download/ro.png /sdcard/RO.png
mv /sdcard/Download/rs.png /sdcard/RS.png
mv /sdcard/Download/ru.png /sdcard/RU.png
mv /sdcard/Download/rw.png /sdcard/RW.png
mv /sdcard/Download/sa.png /sdcard/SA.png
mv /sdcard/Download/sb.png /sdcard/SB.png
mv /sdcard/Download/sc.png /sdcard/SC.png
mv /sdcard/Download/sd.png /sdcard/SD.png
mv /sdcard/Download/se.png /sdcard/SE.png
mv /sdcard/Download/sg.png /sdcard/SG.png
mv /sdcard/Download/sh.png /sdcard/SH.png
mv /sdcard/Download/si.png /sdcard/SI.png
mv /sdcard/Download/sj.png /sdcard/SJ.png
mv /sdcard/Download/sk.png /sdcard/SK.png
mv /sdcard/Download/sl.png /sdcard/SL.png
mv /sdcard/Download/sm.png /sdcard/SM.png
mv /sdcard/Download/sn.png /sdcard/SN.png
mv /sdcard/Download/so.png /sdcard/SO.png
mv /sdcard/Download/sr.png /sdcard/SR.png
mv /sdcard/Download/ss.png /sdcard/SS.png
mv /sdcard/Download/st.png /sdcard/ST.png
mv /sdcard/Download/sv.png /sdcard/SV.png
mv /sdcard/Download/sx.png /sdcard/SX.png
mv /sdcard/Download/sy.png /sdcard/SY.png
mv /sdcard/Download/sz.png /sdcard/SZ.png
mv /sdcard/Download/tc.png /sdcard/TC.png
mv /sdcard/Download/td.png /sdcard/TD.png
mv /sdcard/Download/tf.png /sdcard/TF.png
mv /sdcard/Download/tg.png /sdcard/TG.png
mv /sdcard/Download/th.png /sdcard/TH.png
mv /sdcard/Download/tj.png /sdcard/TJ.png
mv /sdcard/Download/tk.png /sdcard/TK.png
mv /sdcard/Download/tl.png /sdcard/TL.png
mv /sdcard/Download/tm.png /sdcard/TM.png
mv /sdcard/Download/tn.png /sdcard/TN.png
mv /sdcard/Download/to.png /sdcard/TO.png
mv /sdcard/Download/tr.png /sdcard/TR.png
mv /sdcard/Download/tt.png /sdcard/TT.png
mv /sdcard/Download/tv.png /sdcard/TV.png
mv /sdcard/Download/tw.png /sdcard/TW.png
mv /sdcard/Download/tz.png /sdcard/TZ.png
mv /sdcard/Download/ua.png /sdcard/UA.png
mv /sdcard/Download/ug.png /sdcard/UG.png
mv /sdcard/Download/um.png /sdcard/UM.png
mv /sdcard/Download/us.png /sdcard/US.png
mv /sdcard/Download/uy.png /sdcard/UY.png
mv /sdcard/Download/uz.png /sdcard/UZ.png
mv /sdcard/Download/va.png /sdcard/VA.png
mv /sdcard/Download/vc.png /sdcard/VC.png
mv /sdcard/Download/ve.png /sdcard/VE.png
mv /sdcard/Download/vg.png /sdcard/VG.png
mv /sdcard/Download/vi.png /sdcard/VI.png
mv /sdcard/Download/vn.png /sdcard/VN.png
mv /sdcard/Download/vu.png /sdcard/VU.png
mv /sdcard/Download/wf.png /sdcard/WF.png
mv /sdcard/Download/ws.png /sdcard/WS.png
mv /sdcard/Download/xk.png /sdcard/XK.png
mv /sdcard/Download/ye.png /sdcard/YE.png
mv /sdcard/Download/yt.png /sdcard/YT.png
mv /sdcard/Download/za.png /sdcard/ZA.png
mv /sdcard/Download/zm.png /sdcard/ZM.png
mv /sdcard/Download/zw.png /sdcard/ZW.png